# Site settings
title: Nothing ventured, nothing gained
email: thiennguyenit722009@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Little things can make a big difference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thiennguyenenv.github.io" # the base hostname & protocol for your site
twitter_username: Theodore_Nguyen
github_username:  thiennguyenenv

# Build settings
owner:
  name:           Theodore NGUYEN
  avatar:         avatar.jpg
  bio:            "Dream Big And Dare To Fail - Norman Vaughan"
  email:          thiennguyenit722009@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     Asia/Bangkok
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - yekyll-coffeescript
sass:
  sass_dir: _sass
  style: compressed
