# Site settings
title: Nothing ventured, nothing gained
email: thiennguyenit722009@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Little things can make a big difference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thiennguyenenv.github.io" # the base hostname & protocol for your site
twitter_username: Theodore_Nguyen
github_username:  thiennguyenenv

# Build settings
markdown: kramdown
